[project]
name = "simple-agent"
created = "2025-09-16T17:37:46.978317"
framework_version = "0.0.7"

[cli]
version = "1.0.0"
command = "co init"
template = "none"

[agent]
address = "0x0745818023115fb7e32c741e6861650fc503d0dac02b1706d6d54b32192af137"
short_address = "0x0745...f137"
email = "0x07458180@openonion.ai"
email_active = true
created_at = "2025-09-16T17:37:46.978330"
algorithm = "ed25519"
default_model = "gpt-4o-mini"
max_iterations = 10

[auth]
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaWNfa2V5IjoiMHgwNzQ1ODE4MDIzMTE1ZmI3ZTMyYzc0MWU2ODYxNjUwZmM1MDNkMGRhYzAyYjE3MDZkNmQ1NGIzMjE5MmFmMTM3IiwiZXhwIjoyMDczMzY4MjcwLCJpYXQiOjE3NTgwMDgyNzB9.wdmNldj8AnMMjzI8c88Q-iDUWwQb8maV0uFnKAR5rLg"
