[project]
name = "simple-agent"
created = "2025-09-10T15:34:36.756997"
framework_version = "0.0.5"

[cli]
version = "1.0.0"
command = "co create simple-agent"
template = "minimal"

[agent]
address = "0x833a63b24d398da90a146b539d764acd38a944f303bbe53a9b6b2cb411706dda"
short_address = "0x833a...6dda"
email = "0x833a63b2@mail.openonion.ai"
email_active = false
created_at = "2025-09-10T15:34:36.757019"
algorithm = "ed25519"
default_model = "gpt-4o-mini"
max_iterations = 10

[auth]
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaWNfa2V5IjoiMHg4MzNhNjNiMjRkMzk4ZGE5MGExNDZiNTM5ZDc2NGFjZDM4YTk0NGYzMDNiYmU1M2E5YjZiMmNiNDExNzA2ZGRhIiwiZXhwIjoxNzU3NzYxNDk0LCJpYXQiOjE3NTc2NzUwOTR9.E2q9f8tWSEi4mqml0eFWGsTS4-Q0fBHvNGr8WoXV2RE"
