[project]
name = "playwright-agent"
created = "2025-09-13T09:37:43.337091"
framework_version = "0.0.6"

[cli]
version = "1.0.0"
command = "co create playwright-agent"
template = "playwright"

[agent]
address = "0x1d7e83649c6bb9eb2f89deb397bf79aa6a66859f3a078f8ab53f5daaacccba65"
short_address = "0x1d7e...ba65"
email = "0x1d7e8364@mail.openonion.ai"
email_active = true
created_at = "2025-09-13T09:37:43.337105"
algorithm = "ed25519"
default_model = "gpt-4o-mini"
max_iterations = 10

[auth]
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaWNfa2V5IjoiMHgxZDdlODM2NDljNmJiOWViMmY4OWRlYjM5N2JmNzlhYTZhNjY4NTlmM2EwNzhmOGFiNTNmNWRhYWFjY2NiYTY1IiwiZXhwIjoxNzU3ODA2NjYzLCJpYXQiOjE3NTc3MjAyNjN9.QFSjSvyDdXyi471N4ZhBj_EJzWXkL8LuOZ6BAdVdFlo"
