"""
Purpose: Write ConnectOnion's command index into the files Codex and Claude Code always load, so any session in them knows `co` exists (#2113)
LLM-Note:
  Dependencies: imports from [re, pathlib, typer.main, cli/discovery.summary, __version__] | imported by [cli/main.py (co skills index), cli/commands/init.py (co init), cli/commands/doctor_commands.py (co doctor), network/host/server.py (host startup)] | tested by [tests/unit/test_agent_index.py]
  Data flow: stale() reads the version stamp in each target's begin marker → refresh(app) generates the index from the live Typer app only for stale targets → writes between <!-- co:begin <version> --> and <!-- co:end --> | remove() cuts the block back out
  State/Effects: writes ~/.codex/AGENTS.md and ~/.claude/CLAUDE.md, only between the markers, and only when ~/.codex or ~/.claude already exists — a server with no human has neither, so it is never touched
  Integration: one function, refresh(), for co init, co skills index and host startup; stale() for co doctor | the index is generated, never hand-written: one line per visible top-level command, hidden and deprecated ones left out, subcommands left to --help
  Performance: the current-version path reads two small files and runs one regex; the Typer tree is built only when a block must be written
"""

import re
from pathlib import Path
from typing import List, Optional, Tuple

from ... import __version__

END = "<!-- co:end -->"
# The optional leading newline is the blank line _write puts before an
# appended block, so remove() gives back the user's file byte for byte.
_BLOCK = re.compile(r"(\n)?<!-- co:begin (\S+) -->\n.*?<!-- co:end -->\n?", re.S)

RULES = """\
## ConnectOnion (`co`) — generated by `co init`; refresh: `co skills index`; remove: `co skills index --remove`
- You have `co`, the ConnectOnion CLI. Below is every top-level command.
- For outside services (mail, chat, calendars, issue trackers, files), handing work to someone or another machine, or memory: run `co commands` and read `co <cmd> --help` before using a browser or writing a script.
- Don't look for credentials yourself: run the command; if a key is missing, it says how to add it."""


def targets() -> List[Path]:
    """The instruction file of each tool installed here; a tool without its directory is not."""
    home = Path.home()
    return [home / tool / name for tool, name in ((".codex", "AGENTS.md"), (".claude", "CLAUDE.md"))
            if (home / tool).is_dir()]


def _label(cmd) -> str:
    """'Experimental' or 'Preview' when the command's help opens with it, else ''."""
    for text in (cmd.short_help, cmd.help):
        match = re.match(r"\s*(Experimental|Preview)\b", text or "", re.I)
        if match:
            return match.group(1).capitalize()
    return ""


def generate(app) -> str:
    """The rules, then `co <command> — <summary>` per visible top-level command of `app`."""
    import typer.main

    from ..discovery import summary

    lines = []
    for name, cmd in typer.main.get_command(app).commands.items():
        if cmd.hidden or getattr(cmd, "deprecated", False):
            continue
        text, label = summary(cmd), _label(cmd)
        if label and not text.lower().startswith(label.lower()):
            text = f"{label}: {text}"
        lines.append(f"co {name} — {text}")
    return RULES + "\n\n" + "\n".join(lines)


def block(body: str, version: str = __version__) -> str:
    return f"<!-- co:begin {version} -->\n{body}\n{END}\n"


def stamp(path: Path) -> Optional[str]:
    """The version in the file's begin marker, or None when there is no block."""
    if not path.exists():
        return None
    match = _BLOCK.search(path.read_text(encoding="utf-8"))
    return match.group(2) if match else None


def stale() -> List[Tuple[Path, Optional[str]]]:
    """(file, version it carries or None) for every target not at this version."""
    return [(path, old) for path in targets() for old in [stamp(path)] if old != __version__]


def _write(path: Path, new_block: str) -> None:
    """Replace the block in place, or append it after a blank line; nothing else changes."""
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    match = _BLOCK.search(text)
    if match:
        text = text[:match.start()] + (match.group(1) or "") + new_block + text[match.end():]
    elif text:
        text += ("\n" if text.endswith("\n") else "\n\n") + new_block
    else:
        text = new_block
    path.write_text(text, encoding="utf-8")


def refresh(app=None) -> List[Tuple[Path, Optional[str], str]]:
    """Write the block wherever it is missing or stale; (file, old, new) for each one changed."""
    changes = stale()
    if not changes:
        return []
    if app is None:
        from ..main import app
    new_block = block(generate(app))
    for path, _ in changes:
        _write(path, new_block)
    return [(path, old, __version__) for path, old in changes]


def remove() -> List[Path]:
    """Cut the block out of every target; a file left empty was ours and is deleted."""
    removed = []
    for path in targets():
        if stamp(path) is None:
            continue
        text = _BLOCK.sub("", path.read_text(encoding="utf-8"), count=1)
        if text.strip():
            path.write_text(text, encoding="utf-8")
        else:
            path.unlink()
        removed.append(path)
    return removed


def doctor_rows() -> List[Tuple[str, str]]:
    """(severity, text) per target for co doctor: ok, or a warning naming the fix."""
    old = dict(stale())
    rows = []
    for path in targets():
        if path not in old:
            rows.append(("ok", f"{path} at {__version__}"))
        elif old[path] is None:
            rows.append(("warning", f"{path} has no command index for co — Next: co skills index"))
        else:
            rows.append(("warning", f"{path} is stale ({old[path]}, installed {__version__}) — "
                                    f"Next: co skills index"))
    return rows


def handle_skills_index(remove_block: bool = False) -> None:
    """co skills index: print each file changed, and how to undo it."""
    from rich.markup import escape

    from ..style import console, next_line
    out = console()
    if not targets():
        out.print("Neither ~/.codex nor ~/.claude exists here, so nothing was written.", markup=False)
        out.print(next_line("co skills --help"))
        return
    if remove_block:
        removed = remove()
        for path in removed:
            out.print(f"Removed the command index for co from {escape(str(path))}")
        if not removed:
            out.print("No command index for co to remove.")
        out.print(next_line("co skills index"))
        return
    changed = refresh()
    for path, old, new in changed:
        out.print(f"Wrote the command index for co to {escape(str(path))} ({old or 'none'} → {new})")
    for path in targets():
        if path not in [p for p, _, _ in changed]:
            out.print(f"{escape(str(path))} already has the index for {__version__}")
    out.print("Only the text between <!-- co:begin --> and <!-- co:end --> is ours. "
              "To take it out: co skills index --remove", markup=False)
    out.print(next_line("co doctor"))
