[project]
name = "email-agent"
created = "2025-09-13T10:55:38.988615"
framework_version = "0.0.7"

[cli]
version = "1.0.0"
command = "co init"
template = "none"

[agent]
address = "0x6fdb2d9ece1fa83083de00ad49cdd4d75f4da6e79c363e1b6b3bd51c0b9aab74"
short_address = "0x6fdb...ab74"
email = "0x6fdb2d9e@mail.openonion.ai"
email_active = true
created_at = "2025-09-13T10:55:38.988628"
algorithm = "ed25519"
default_model = "gpt-4o-mini"
max_iterations = 10

[auth]
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaWNfa2V5IjoiMHg2ZmRiMmQ5ZWNlMWZhODMwODNkZTAwYWQ0OWNkZDRkNzVmNGRhNmU3OWMzNjNlMWI2YjNiZDUxYzBiOWFhYjc0IiwiZXhwIjoxNzU3ODExMzM5LCJpYXQiOjE3NTc3MjQ5Mzl9.kMFMfXrF0H4--_o8yyGkocFEy7F1tpnETiKyKjIWrcQ"
