"""co handoff (#2351): drafting from real session formats, preview vs --yes, recipients,
the credential scan, and the recipient's inbox/show/open over a faked mailbox."""

import json
import re
import sys
import textwrap
from pathlib import Path

import pytest
from typer.testing import CliRunner

from connectonion.cli.main import app
from connectonion.handoff import bundle as bundles
from connectonion.handoff import opener, sessions, transport

runner = CliRunner()
THREAD = "01a12594-63de-7210-809d-2a727b96f400"
SELF = "me@mail.openonion.ai"


def _invoke(*args):
    return runner.invoke(app, list(args), env={"COLUMNS": "200", "NO_COLOR": "1"})


@pytest.fixture
def project(tmp_path, monkeypatch):
    for name in ("CODEX_THREAD_ID", "CLAUDE_CODE_SESSION_ID", "CODEX_HOME"):
        monkeypatch.delenv(name, raising=False)
    monkeypatch.setenv("AGENT_EMAIL", SELF)
    folder = tmp_path / "login-app"
    folder.mkdir()
    monkeypatch.chdir(folder)
    return folder.resolve()


def _row(kind, payload, when="2026-10-10T10:00:00Z"):
    return json.dumps({"timestamp": when, "type": kind, "payload": payload})


def _codex_message(role, text):
    kind = "input_text" if role == "user" else "output_text"
    return _row("response_item", {"type": "message", "role": role, "content": [{"type": kind, "text": text}]})


def write_codex_session(cwd: Path, extra: str = "") -> Path:
    folder = Path.home() / ".codex" / "sessions" / "2026" / "10" / "10"
    folder.mkdir(parents=True)
    path = folder / f"rollout-2026-10-10T10-00-00-{THREAD}.jsonl"
    rows = [
        _row("session_meta", {"id": THREAD, "cwd": str(cwd), "originator": "codex-tui", "source": "cli"}),
        _codex_message("user", "# AGENTS.md instructions\n\n<INSTRUCTIONS>house rules</INSTRUCTIONS>"),
        _codex_message("user", "Option A: httpOnly cookie. Option B: localStorage. Which for the login token?" + extra),
        _row("response_item", {"type": "function_call", "name": "shell", "arguments": "{}"}),
        _codex_message("assistant", "Reject B: any XSS can read localStorage. Go with A, the cookie."),
        _codex_message("user", "Agreed. Next is the middleware in auth/session.py."),
    ]
    path.write_text("\n".join(rows) + "\n")
    return path


def write_claude_session(cwd: Path) -> Path:
    folder = Path.home() / ".claude" / "projects" / re.sub(r"[^A-Za-z0-9]", "-", str(cwd))
    folder.mkdir(parents=True)
    path = folder / "5b2c.jsonl"
    rows = [
        {"type": "user", "isMeta": True, "timestamp": "2026-10-10T10:00:00Z",
         "message": {"role": "user", "content": "Caveat: The messages below were generated by the user"}},
        {"type": "user", "timestamp": "2026-10-10T10:00:01Z", "cwd": str(cwd),
         "message": {"role": "user", "content": "Should we retry with backoff or a queue?"}},
        {"type": "assistant", "timestamp": "2026-10-10T10:00:02Z",
         "message": {"role": "assistant", "content": [{"type": "thinking", "thinking": "hidden"},
                                                      {"type": "text", "text": "Queue: backoff loses jobs on restart."}]}},
        {"type": "assistant", "isSidechain": True, "timestamp": "2026-10-10T10:00:03Z",
         "message": {"role": "assistant", "content": [{"type": "text", "text": "subagent chatter"}]}},
    ]
    path.write_text("\n".join(json.dumps(r) for r in rows) + "\n")
    return path


@pytest.fixture
def model(monkeypatch):
    """The one llm_do call, faked: records the prompt and returns a fixed draft."""
    prompts = []

    def fake_llm_do(prompt, output=None, **kwargs):
        prompts.append(prompt)
        return bundles.Draft(
            title="Store the login token",
            task="Store the login session token; done when the cookie is set on login.",
            may_do=["edit auth/"],
            where_it_stands="Option chosen, no code yet",
            decided=[bundles.Decided(decision="Use an httpOnly cookie", why="JS cannot read it")],
            rejected=[bundles.Rejected(option="B: localStorage", why_not="any XSS can read localStorage")],
            open_questions=["Cookie lifetime?"],
            references=[bundles.Reference(reference="auth/session.py", note="where the middleware goes")],
        )

    import connectonion.llm_do  # noqa: F401  (the module, not the function the package re-exports)
    monkeypatch.setattr(sys.modules["connectonion.llm_do"], "llm_do", fake_llm_do)
    return prompts


@pytest.fixture
def mailbox(monkeypatch):
    """The agent mailbox, faked at the transport's two functions."""
    mails = []

    def deliver(to, subject, body, idempotency_key):
        mails.append({"id": str(len(mails) + 1), "from": SELF, "to": to, "subject": subject,
                      "message": body, "timestamp": "2026-10-10T10:05:00"})
        return {"success": True, "message_id": f"msg-{len(mails)}", "from": SELF}

    monkeypatch.setattr(transport, "deliver", deliver)
    monkeypatch.setattr(transport, "fetch", lambda last=200: [m for m in reversed(mails)
                                                              if m["subject"].startswith(transport.SUBJECT_PREFIX)])
    monkeypatch.setattr("connectonion.cli.commands.project_cmd_lib.load_api_key", lambda: "token")
    monkeypatch.setattr(transport, "my_address", lambda: "0x" + "ab" * 32)
    return mails


def _draft_id(output: str) -> str:
    return re.search(r"--draft (ho-[0-9a-f]{8}) --yes", output).group(1)


# ---- reading sessions ----

def test_reads_the_codex_session_for_this_directory(project):
    path = write_codex_session(project)
    agent, found = sessions.find_session(project)
    assert (agent, found) == ("codex", path)
    turns = sessions.read_turns(agent, found)
    assert [t["role"] for t in turns] == ["user", "assistant", "user"]
    assert "AGENTS.md" not in json.dumps(turns)
    assert "Reject B" in turns[1]["text"]


def test_a_codex_session_in_another_directory_is_not_used(project, tmp_path):
    write_codex_session(tmp_path / "elsewhere")
    with pytest.raises(sessions.SessionNotFound):
        sessions.find_session(project)


def test_reads_the_claude_code_session_for_this_directory(project):
    path = write_claude_session(project)
    agent, found = sessions.find_session(project, "claude")
    assert (agent, found) == ("claude", path)
    turns = sessions.read_turns(agent, found)
    assert [t["text"] for t in turns] == ["Should we retry with backoff or a queue?",
                                          "Queue: backoff loses jobs on restart."]


# ---- preview vs --yes ----

def test_send_previews_by_default_and_sends_nothing(project, model, mailbox):
    write_codex_session(project)
    result = _invoke("handoff", "send", SELF, "the login token task")
    assert result.exit_code == 0, result.output
    assert mailbox == []
    assert "Nothing has been sent" in result.output
    assert "any XSS can read localStorage" in result.output        # the excerpt and decision, shown
    assert "Which for the login token?" in result.output
    assert "Which for the login token?" in model[0]                  # the draft saw the excerpt
    draft = Path.home() / ".co" / "handoff" / "drafts" / f"{_draft_id(result.output)}.json"
    assert json.loads(draft.read_text())["to"] == SELF


def test_yes_with_draft_sends_exactly_the_previewed_bundle(project, model, mailbox):
    write_codex_session(project)
    preview = _invoke("handoff", "send", SELF, "the login token task")
    handoff_id = _draft_id(preview.output)
    sent = _invoke("handoff", "send", SELF, "--draft", handoff_id, "--yes")
    assert sent.exit_code == 0, sent.output
    assert len(mailbox) == 1 and len(model) == 1                     # no second drafting call
    arrived = bundles.from_mail(mailbox[0]["message"])
    previewed = json.loads((Path.home() / ".co/handoff/drafts" / f"{handoff_id}.json").read_text())
    assert arrived["verified"] and arrived["content_hash"] == previewed["content_hash"]
    assert f"Next: co handoff status {handoff_id}" in sent.output


def test_a_draft_is_bound_to_its_recipient(project, model, mailbox):
    write_codex_session(project)
    handoff_id = _draft_id(_invoke("handoff", "send", SELF, "task").output)
    result = _invoke("handoff", "send", "someone@example.com", "--draft", handoff_id, "--yes")
    assert result.exit_code == 1 and mailbox == []


def test_from_file_drafts_without_a_session(project, model, mailbox, tmp_path):
    notes = tmp_path / "notes.md"
    notes.write_text("We rejected B because of XSS.")
    result = _invoke("handoff", "send", SELF, "--from-file", str(notes))
    assert result.exit_code == 0, result.output
    assert "We rejected B because of XSS." in model[0]


def test_no_session_names_the_from_file_fallback(project, model, mailbox):
    result = _invoke("handoff", "send", SELF, "task")
    assert result.exit_code == 1
    assert "--from-file" in result.output and model == []


# ---- recipients ----

def test_an_unknown_name_exits_1_with_the_command_to_add_it(project, model, mailbox):
    result = _invoke("handoff", "send", "ody", "task")
    assert result.exit_code == 1
    assert "Next: co handoff contact ody <their-email-or-0x-address>" in result.output
    assert model == []


def test_a_contact_name_resolves_to_its_address(project, model, mailbox):
    assert _invoke("handoff", "contact", "Ody", "ody@example.com").exit_code == 0
    assert transport.resolve("ody") == "ody@example.com"


def test_a_0x_address_resolves_to_that_agents_mailbox():
    address = "0xadfeca14cb" + "c" * 54
    assert transport.resolve(address) == "0xadfeca14cb@mail.openonion.ai"   # oo-api: 0x + 10 hex
    with pytest.raises(ValueError):
        transport.resolve("0xshort")


# ---- privacy ----

def test_a_credential_in_the_session_is_refused(project, model, mailbox):
    write_codex_session(project, extra=" My key is sk-proj-" + "a1B2" * 8)
    result = _invoke("handoff", "send", SELF, "task", "--yes")
    assert result.exit_code == 1
    assert "Refusing to send" in result.output and "OpenAI/Anthropic-style key" in result.output
    assert mailbox == []


def test_a_value_from_keys_env_is_refused_even_without_a_known_shape(monkeypatch):
    monkeypatch.setenv("LINEAR_API_KEY", "plainvalue-without-prefix-123")
    bundle = {"excerpt": [{"text": "here: plainvalue-without-prefix-123"}]}
    from connectonion.cli.commands.handoff_commands import _known_secrets
    assert bundles.find_credentials(bundle, _known_secrets()) == ["excerpt[0].text: a value from your keys.env"]


def test_a_changed_bundle_is_not_verified():
    bundle = bundles.seal({"format": bundles.FORMAT, "id": "ho-1", "title": "t", "task": "g", "from": "a", "to": "b",
                           "created_at": "2026-10-10", "where_it_stands": ""})
    subject, body = bundles.to_mail(bundle, "prompt")
    assert bundles.from_mail(body)["verified"]
    tampered = dict(bundle, task="something else")          # keeps the approved hash
    assert not bundles.from_mail(bundles.to_mail(tampered, "prompt")[1])["verified"]


# ---- recipient ----

def test_inbox_show_and_open_from_the_mailbox(project, model, mailbox, monkeypatch):
    write_codex_session(project)
    handoff_id = _draft_id(_invoke("handoff", "send", SELF, "task").output)
    _invoke("handoff", "send", SELF, "--draft", handoff_id, "--yes")

    inbox = _invoke("handoff", "inbox")
    assert handoff_id in inbox.output and f"Next: co handoff show {handoff_id}" in inbox.output

    summary = _invoke("handoff", "show", handoff_id)
    assert "Store the login token" in summary.output and "localStorage" not in summary.output
    detail = _invoke("handoff", "show", handoff_id, "--decisions")
    assert "- B: localStorage: any XSS can read localStorage" in detail.output

    seeds = []

    def fake_start(agent, prompt, cwd):
        seeds.append((agent, prompt, cwd))
        return {"session": "thread-1", "reply": "Goal: store the token.",
                "resume": f"cd {cwd} && codex resume thread-1", "ask": "codex exec resume thread-1 \"q\""}

    monkeypatch.setattr(opener, "start", fake_start)
    monkeypatch.setattr("shutil.which", lambda name: f"/usr/bin/{name}")
    opened = _invoke("handoff", "open", handoff_id)
    assert opened.exit_code == 0, opened.output
    assert "codex resume thread-1" in opened.output
    agent, prompt, cwd = seeds[0]
    assert agent == "codex" and "any XSS can read localStorage" in prompt
    assert (cwd / "HANDOFF.md").exists() and (cwd / "excerpt.md").exists()

    again = _invoke("handoff", "open", handoff_id)
    assert len(seeds) == 1 and "No new session was created" in again.output


def test_show_of_an_unknown_id_points_at_the_inbox(project, mailbox):
    result = _invoke("handoff", "show", "ho-00000000")
    assert result.exit_code == 1 and "Next: co handoff inbox" in result.output


# ---- compaction and picking a session ----

def test_a_compacted_codex_session_keeps_what_codex_retained_then_the_turns_after(project):
    path = write_codex_session(project)
    rows = path.read_text().splitlines()
    compacted = _row("compacted", {"message": "", "replacement_history": [
        {"type": "message", "role": "user", "content": [{"type": "input_text", "text": "Original ask: store the login token."}]},
        {"type": "message", "role": "user", "content": [{"type": "input_text", "text": "# AGENTS.md instructions\nrules"}]},
        {"type": "compaction", "encrypted_content": "gAAAA-opaque"}]})
    after = _codex_message("user", "After compaction: lifetime is 7 days.")
    path.write_text("\n".join(rows + [compacted, after]) + "\n")
    turns = sessions.excerpt(sessions.read_turns("codex", path))
    assert [(t["role"], t["text"]) for t in turns] == [
        ("earlier", "Original ask: store the login token."),
        ("user", "After compaction: lifetime is 7 days.")]


def test_a_compacted_claude_session_starts_from_its_summary(project):
    path = write_claude_session(project)
    rows = path.read_text().splitlines()
    summary = {"type": "user", "isCompactSummary": True, "timestamp": "2026-10-10T11:00:00Z",
               "message": {"role": "user", "content": "This session is being continued from a previous "
                                                      "conversation.\n\nSummary: chose the queue over backoff."}}
    after = {"type": "user", "timestamp": "2026-10-10T11:00:01Z",
             "message": {"role": "user", "content": "Now write the worker."}}
    path.write_text("\n".join(rows + [json.dumps(summary), json.dumps(after)]) + "\n")
    turns = sessions.excerpt(sessions.read_turns("claude", path))
    assert [t["role"] for t in turns] == ["summary", "user"]
    assert "chose the queue over backoff" in turns[0]["text"]


def test_a_long_session_keeps_the_last_turns_but_never_drops_the_summary():
    turns = [{"role": "summary", "text": "S", "timestamp": ""}] + \
            [{"role": "user", "text": str(i), "timestamp": ""} for i in range(100)]
    kept = sessions.excerpt(turns, limit=5)
    assert [t["text"] for t in kept] == ["S", "95", "96", "97", "98", "99"]


def test_session_by_id_or_path(project, tmp_path):
    path = write_codex_session(tmp_path / "another-project")
    assert sessions.find_by_id(THREAD) == ("codex", path)
    assert sessions.find_by_id(str(path)) == ("codex", path.resolve())
    claude = write_claude_session(project)
    assert sessions.find_by_id("5b2c") == ("claude", claude)


def test_send_from_another_session_does_not_put_local_paths_in_the_bundle(project, model, mailbox, tmp_path):
    write_codex_session(tmp_path / "another-project")
    result = _invoke("handoff", "send", SELF, "task", "--session", THREAD)
    assert result.exit_code == 0, result.output
    draft = json.loads((Path.home() / ".co/handoff/drafts" / f"{_draft_id(result.output)}.json").read_text())
    assert draft["source"] == {"kind": "codex", "session": THREAD, "turns_included": 3, "compacted": False}
    assert str(Path.home()) not in json.dumps(draft)


# ---- what must never be mailed ----

def test_a_planted_sk_test_key_is_refused(project, model, mailbox):
    write_codex_session(project, extra=" use sk-test-4f9a8b7c6d5e4f3a2b1c")
    result = _invoke("handoff", "send", SELF, "task", "--yes")
    assert result.exit_code == 1 and "Refusing to send" in result.output and mailbox == []


def test_an_invite_code_is_refused_by_shape_and_by_value(project, model, mailbox, monkeypatch):
    # A holder of the invite becomes a contact, and contacts may EXEC on the host.
    from connectonion.network.host.server import EXEC_REQUIRES
    assert "contact" in EXEC_REQUIRES
    write_codex_session(project, extra=" the invite is ABCDE-FGHJK-MNPQR")
    result = _invoke("handoff", "send", SELF, "task", "--yes")
    assert result.exit_code == 1 and "ConnectOnion invite code" in result.output and mailbox == []
    monkeypatch.setenv("CO_INVITE_CODE", "OpenOnion-legacy-code")
    assert bundles.find_credentials({"t": "code OpenOnion-legacy-code"},
                                    __import__("connectonion.cli.commands.handoff_commands",
                                               fromlist=["_known_secrets"])._known_secrets())


def test_the_mail_carries_no_invite_code_or_token(project, model, mailbox, monkeypatch):
    monkeypatch.setenv("CO_INVITE_CODE", "ZZZZZ-YYYYY-XXXXX")
    monkeypatch.setenv("OPENONION_API_KEY", "eyJhbGciOiJIUzI1NiJ9.payload-part-x.signature-part")
    write_codex_session(project)
    handoff_id = _draft_id(_invoke("handoff", "send", SELF, "task").output)
    _invoke("handoff", "send", SELF, "--draft", handoff_id, "--yes")
    mail = mailbox[0]["subject"] + mailbox[0]["message"]
    assert "ZZZZZ-YYYYY-XXXXX" not in mail and "eyJhbGciOiJIUzI1NiJ9" not in mail
    assert "invite" not in mail.lower()


def test_private_paths_are_shown_in_the_preview(project, model, mailbox):
    write_codex_session(project, extra=" see /Users/alice/secret-notes/plan.md")
    result = _invoke("handoff", "send", SELF, "task")
    assert result.exit_code == 0
    assert "Private paths in it" in result.output and "/Users/alice/secret-notes/plan.md" in result.output


def test_claude_open_reads_the_result_event_from_claude_codes_event_list(monkeypatch, tmp_path):
    # Claude Code 2.1.290 prints [system, assistant, ..., result]; older versions printed the result alone.
    events = [{"type": "system"}, {"type": "result", "session_id": "s-1", "result": "Goal: ..."}]
    monkeypatch.setattr(opener.subprocess, "run", lambda *a, **k: opener.subprocess.CompletedProcess(
        a, 0, stdout=json.dumps(events), stderr=""))
    started = opener.start("claude", "seed", tmp_path)
    assert started["session"] == "s-1" and "claude --resume s-1" in started["resume"]


# ---- a handoff sent to an ordinary email (#2378) ----

def _sent_to_a_personal_address(project, mailbox) -> dict:
    write_codex_session(project)
    handoff_id = _draft_id(_invoke("handoff", "send", "ody@gmail.com", "task").output)
    _invoke("handoff", "send", "ody@gmail.com", "--draft", handoff_id, "--yes")
    return mailbox[-1]


def _fake_open(monkeypatch) -> list:
    seeds = []

    def fake_start(agent, prompt, cwd):
        seeds.append((agent, prompt, cwd))
        return {"session": "thread-1", "reply": "Goal.", "resume": "codex resume thread-1", "ask": "codex exec resume thread-1"}

    monkeypatch.setattr(opener, "start", fake_start)
    monkeypatch.setattr("shutil.which", lambda name: f"/usr/bin/{name}")
    monkeypatch.setattr(transport, "fetch", lambda last=200: [])   # not in the recipient's agent mailbox
    return seeds


def test_the_mail_to_a_personal_address_is_a_prompt_that_needs_no_mailbox(project, model, mailbox):
    # #2378: nothing in it depends on where the mail landed.
    mail = _sent_to_a_personal_address(project, mailbox)
    assert mail["message"].startswith("<pre>Paste this into Codex or Claude Code")
    assert "co handoff inbox" not in mail["message"] and "&lt;" not in mail["message"]


def test_open_a_handoff_from_the_mail_as_co_email_read_prints_it(project, model, mailbox, monkeypatch, tmp_path):
    mail = _sent_to_a_personal_address(project, mailbox)
    seeds = _fake_open(monkeypatch)
    # The mail service joins single newlines, and the terminal re-wraps at its width,
    # which can break a line inside the BEGIN marker (seen on a real 1.9.2b5 mail).
    printed = " ".join(mail["message"].split("\n")).replace("----- BEGIN", "-----\nBEGIN")
    saved = tmp_path / "handoff-mail.txt"
    saved.write_text(f"From: me\nSubject: {mail['subject']}\n\n" + textwrap.fill(printed, 80), encoding="utf-8")

    opened = _invoke("handoff", "open", str(saved))
    assert opened.exit_code == 0, opened.output
    assert seeds and "any XSS can read localStorage" in seeds[0][1]
    assert (seeds[0][2] / "HANDOFF.md").exists()


@pytest.mark.parametrize("encoding", ["quoted-printable", "base64"])
def test_open_a_handoff_from_a_downloaded_eml(project, model, mailbox, monkeypatch, tmp_path, encoding):
    from email.message import EmailMessage
    mail = _sent_to_a_personal_address(project, mailbox)
    seeds = _fake_open(monkeypatch)
    message = EmailMessage()
    message["Subject"] = mail["subject"]
    message.set_content(mail["message"], cte=encoding)   # what a mail client's "Download message" saves
    saved = tmp_path / "handoff.eml"
    saved.write_bytes(message.as_bytes())

    opened = _invoke("handoff", "open", str(saved))
    assert opened.exit_code == 0, opened.output
    assert seeds


def test_a_file_without_a_handoff_says_so(project, mailbox, tmp_path):
    saved = tmp_path / "notes.txt"
    saved.write_text("just notes", encoding="utf-8")
    result = _invoke("handoff", "open", str(saved))
    assert result.exit_code == 1 and "no handoff in" in result.output.lower()
